"use client";

import { useState } from "react";
import { X, Database, Code2, DollarSign, Layers, GitBranch, Target, BookOpen, Copy, Check } from "lucide-react";
import { toast } from "sonner";
import { haptics } from "@/lib/haptics";
import type { Idea } from "@/lib/types";
import { cn, skillLevelColor, complexityLabel, complexityColor } from "@/lib/utils";

interface Props {
  idea: Idea;
  open: boolean;
  onClose: () => void;
}

function buildCopyText(idea: Idea): string {
  const lines: string[] = [
    `# ${idea.title}`,
    `Level: ${idea.skillLevel.charAt(0) + idea.skillLevel.slice(1).toLowerCase()} · Complexity: ${idea.complexityScore}/10 · ${idea.timeEstimate} · ${idea.teamSize}`,
    "",
    "## Problem Solved",
    idea.problemSolved,
  ];
  if (idea.mvpScope)            lines.push("", "## MVP Scope", idea.mvpScope);
  if (idea.coreFeatures.length) { lines.push("", "## Core Features"); idea.coreFeatures.forEach((f) => lines.push(`  ✓ ${f}`)); }
  if (idea.architecture)        lines.push("", "## Architecture", idea.architecture);
  if (idea.recommendedStack.length) lines.push("", "## Recommended Stack", idea.recommendedStack.join(", "));
  if (idea.dbRecommendation)    lines.push("", "## Database", idea.dbRecommendation);
  if (idea.suggestedApis.length)  { lines.push("", "## APIs & Services"); idea.suggestedApis.forEach((a) => lines.push(`  → ${a}`)); }
  if (idea.stretchGoals.length)   { lines.push("", "## Stretch Goals"); idea.stretchGoals.forEach((g) => lines.push(`  ★ ${g}`)); }
  if (idea.monetizationIdeas.length) { lines.push("", "## Monetization"); idea.monetizationIdeas.forEach((m) => lines.push(`  $ ${m}`)); }
  if (idea.learningOutcomes.length)  { lines.push("", "## Learning Outcomes"); idea.learningOutcomes.forEach((l) => lines.push(`  • ${l}`)); }
  if (idea.prerequisites.length) lines.push("", "## Prerequisites", idea.prerequisites.join(", "));
  lines.push("", "---", "Generated by ForgeFlow");
  return lines.join("\n");
}

export function IdeaExpandDialog({ idea, open, onClose }: Props) {
  const [copied, setCopied] = useState(false);

  if (!open) return null;

  async function handleCopy() {
    try {
      await navigator.clipboard.writeText(buildCopyText(idea));
      setCopied(true);
      haptics.success();
      toast.success("Blueprint copied to clipboard");
      setTimeout(() => setCopied(false), 2000);
    } catch {
      toast.error("Failed to copy — try selecting the text manually");
    }
  }

  return (
    <div
      className="fixed inset-0 z-50 flex items-end sm:items-center justify-center p-0 sm:p-4 bg-black/60 backdrop-blur-sm animate-fade-in"
      onClick={onClose}
    >
      {/* Modal — always light surface for readability */}
      <div
        className="rounded-t-2xl sm:rounded-2xl w-full sm:max-w-2xl max-h-[92dvh] overflow-y-auto animate-dialog-in"
        style={{
          background: "linear-gradient(160deg, #f0fdf4 0%, #ffffff 45%, #f8faff 100%)",
          boxShadow: "0 24px 64px -8px rgba(0,0,0,0.22), 0 4px 16px rgba(0,0,0,0.10)",
          border: "1px solid rgba(187,247,208,0.6)",
        }}
        onClick={(e) => e.stopPropagation()}
      >
        {/* Sticky header */}
        <div
          className="sticky top-0 z-10 px-6 py-4 flex items-start justify-between gap-4 rounded-t-2xl"
          style={{
            background: "rgba(240,253,244,0.92)",
            backdropFilter: "blur(16px)",
            borderBottom: "1px solid rgba(187,247,208,0.7)",
          }}
        >
          <div className="flex-1 min-w-0">
            <h2 className="font-bold text-lg text-gray-900 truncate">{idea.title}</h2>
            <div className="flex items-center gap-2 mt-1.5 flex-wrap">
              <span className={cn("text-xs font-medium px-2 py-0.5 rounded-full border", skillLevelColor(idea.skillLevel))}>
                {idea.skillLevel.charAt(0) + idea.skillLevel.slice(1).toLowerCase()}
              </span>
              <span className={cn("text-xs font-medium", complexityColor(idea.complexityScore))}>
                {complexityLabel(idea.complexityScore)} · {idea.complexityScore}/10
              </span>
              <span className="text-xs text-gray-500">{idea.timeEstimate}</span>
            </div>
          </div>

          <div className="flex items-center gap-1.5 shrink-0">
            <button
              onClick={handleCopy}
              className={cn(
                "flex items-center gap-1.5 px-3 h-8 rounded-lg text-xs font-medium transition-all border",
                copied
                  ? "bg-green-100 text-green-700 border-green-200"
                  : "bg-white/80 text-gray-600 border-gray-200 hover:bg-white hover:text-gray-900"
              )}
              style={{ backdropFilter: "blur(8px)" }}
              title="Copy blueprint"
            >
              {copied
                ? <><Check className="w-3.5 h-3.5" />Copied</>
                : <><Copy className="w-3.5 h-3.5" />Copy</>}
            </button>

            <button
              onClick={onClose}
              className="w-8 h-8 flex items-center justify-center rounded-lg bg-white/80 border border-gray-200 text-gray-500 hover:text-gray-900 hover:bg-white transition-colors"
              style={{ backdropFilter: "blur(8px)" }}
              title="Close"
            >
              <X className="w-4 h-4" />
            </button>
          </div>
        </div>

        {/* Body */}
        <div className="px-6 py-5 space-y-6">
          <Section icon={Target} title="Problem Solved">
            <p className="text-sm text-gray-700 leading-relaxed">{idea.problemSolved}</p>
          </Section>

          {idea.mvpScope && (
            <Section icon={Layers} title="MVP Scope">
              <p className="text-sm text-gray-700 leading-relaxed">{idea.mvpScope}</p>
            </Section>
          )}

          {idea.coreFeatures.length > 0 && (
            <Section icon={Code2} title="Core Features">
              <ul className="space-y-2">
                {idea.coreFeatures.map((f) => (
                  <li key={f} className="text-sm text-gray-700 flex gap-2.5">
                    <span className="text-emerald-600 mt-0.5 shrink-0 font-bold">✓</span>
                    {f}
                  </li>
                ))}
              </ul>
            </Section>
          )}

          {idea.architecture && (
            <Section icon={GitBranch} title="Suggested Architecture">
              <p className="text-sm text-gray-700 leading-relaxed">{idea.architecture}</p>
            </Section>
          )}

          <Section icon={Code2} title="Recommended Stack">
            <div className="flex flex-wrap gap-2">
              {idea.recommendedStack.map((tech) => (
                <span key={tech} className="text-xs bg-indigo-50 text-indigo-700 border border-indigo-100 px-2.5 py-1 rounded-lg font-medium">
                  {tech}
                </span>
              ))}
            </div>
          </Section>

          {idea.dbRecommendation && (
            <Section icon={Database} title="Database Recommendation">
              <p className="text-sm text-gray-700 leading-relaxed">{idea.dbRecommendation}</p>
            </Section>
          )}

          {idea.suggestedApis.length > 0 && (
            <Section icon={Code2} title="APIs & Services">
              <ul className="space-y-1.5">
                {idea.suggestedApis.map((api) => (
                  <li key={api} className="text-sm text-gray-700 flex gap-2">
                    <span className="text-gray-400 shrink-0">→</span>
                    {api}
                  </li>
                ))}
              </ul>
            </Section>
          )}

          {idea.stretchGoals.length > 0 && (
            <Section icon={Layers} title="Stretch Goals">
              <ul className="space-y-1.5">
                {idea.stretchGoals.map((g) => (
                  <li key={g} className="text-sm text-gray-700 flex gap-2">
                    <span className="text-amber-500 shrink-0">★</span>
                    {g}
                  </li>
                ))}
              </ul>
            </Section>
          )}

          {idea.monetizationIdeas.length > 0 && (
            <Section icon={DollarSign} title="Monetization Ideas">
              <ul className="space-y-1.5">
                {idea.monetizationIdeas.map((m) => (
                  <li key={m} className="text-sm text-gray-700 flex gap-2">
                    <span className="text-emerald-600 shrink-0 font-semibold">$</span>
                    {m}
                  </li>
                ))}
              </ul>
            </Section>
          )}

          {idea.learningOutcomes.length > 0 && (
            <Section icon={BookOpen} title="Learning Outcomes">
              <ul className="space-y-1.5">
                {idea.learningOutcomes.map((l) => (
                  <li key={l} className="text-sm text-gray-700 flex gap-2">
                    <span className="text-indigo-500 shrink-0">•</span>
                    {l}
                  </li>
                ))}
              </ul>
            </Section>
          )}

          {idea.prerequisites.length > 0 && (
            <div className="rounded-xl p-4" style={{ background: "rgba(240,253,244,0.8)", border: "1px solid rgba(187,247,208,0.8)" }}>
              <p className="text-xs font-semibold text-gray-800 mb-2">Prerequisites</p>
              <div className="flex flex-wrap gap-2">
                {idea.prerequisites.map((p) => (
                  <span key={p} className="text-xs bg-white text-gray-600 border border-gray-200 px-2.5 py-1 rounded-lg">
                    {p}
                  </span>
                ))}
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}

function Section({ icon: Icon, title, children }: { icon: React.ElementType; title: string; children: React.ReactNode }) {
  return (
    <div>
      <div className="flex items-center gap-2 mb-3">
        <div className="w-6 h-6 rounded-md bg-emerald-50 border border-emerald-100 flex items-center justify-center">
          <Icon className="w-3.5 h-3.5 text-emerald-600" />
        </div>
        <h3 className="text-sm font-semibold text-gray-900">{title}</h3>
      </div>
      {children}
    </div>
  );
}
